- production-antora-playbook.yml
- staging-antora-playbook.yml
Updated the production and staging playbooks to reflect the latest Operator branches.
> Update Operator branches

- production-antora-playbook.yml
- staging-antora-playbook.yml
- add CBL release/1.3 branch
- add SG release/1.4 release/1.3 branches
> Update staging and production playbooks

- production-antora-playbook.yml
- staging-antora-playbook.yml
The repo has moved from couchbaselabs to couchbase.
> Update es-connector source URL.

- staging-antora-playbook.yml
1.1.0 is now forked, this adds in the branch to staging, master now
becomes 1.2.0.
> Update Operator Staging

- home/modules/ROOT/pages/index.adoc
- home/modules/contribute/pages/basics.adoc
> DOC-4229 : Remove pre-release label

- staging-antora-playbook.yml
Reverts couchbase/docs-site#22
> Revert "add tutorials to playbooks"

- lib/json-config-ui-block-macro.js
A minor change to ensure this extension works in a future version of Asciidoctor.js.
> future proof json-config-ui block macro extension to work with Asciidoctor.js

- Dockerfile.jenkins
- Jenkinsfile
- home/modules/contribute/pages/attributes-and-roles.adoc
- home/modules/contribute/pages/basics.adoc
- home/modules/contribute/pages/build-site.adoc
- home/modules/contribute/pages/code-blocks.adoc
- home/modules/contribute/pages/cross-references.adoc
- home/modules/contribute/pages/includes.adoc
- home/modules/contribute/pages/install-antora.adoc
- home/modules/contribute/pages/test-site.adoc
- home/modules/contribute/pages/workflow-overview.adoc
- netlify.toml
- netlify/package.json
- netlify/yarn.lock
- package.json
* upgrade Netlify build (deploy previews) to Antora 2
* remove workaround that injects GITHUB_TOKEN into playbook in Netlify build
* configure Jenkins pipeline for production build
* upgrade Jenkins build to Antora 2
* create custom Docker image based on Antora image for use in Jenkins job
* switch builds to Node 10
* populate GIT_CREDENTIALS environment variable in Jenkins job
> upgrade to Antora 2 and switch to Jenkins pipeline

- production-antora-playbook.yml
This reverts commit 5965c847c1f57659621403441e516f65a73eaa64.
> Revert "Update backup repo branch to use alice (#54)"

- lib/tabs-block.js
- remove repeating - characters in generated ID
- remove leading and trailing - in generated ID
> fix ID generation in tabs extension

- production-antora-playbook.yml
- staging-antora-playbook.yml
Added tutorial repository references to staging-antora-playbook.yml and production-antora-playbook.yml.
> Publishing User Profile Xamarin Tutorial

- Dockerfile.jenkins
- Jenkinsfile
- netlify.toml
- netlify/package-lock.json
- netlify/package.json
- package-lock.json
- package.json
- add @antora/xref-validator to Docker image for production build
- add @antora/xref-validator to Netlify build
- configure staging build to use xref validator
- configure production build to use xref validator
- add @antora/xref-validator to authoring tools
> enable xref validator in staging and production site

- production-antora-playbook.yml
- staging-antora-playbook.yml
https://issues.couchbase.com/browse/DOC-5560
> DOC-5560 - replace `master` with `release/2.3`

- production-antora-playbook.yml
- staging-antora-playbook.yml
https://issues.couchbase.com/browse/DOC-5560
> DOC-5560 - spark connector release 2.4

- production-antora-playbook.yml
- staging-antora-playbook.yml
There are no functional changes. This just updates to the UI bundle produced with Gulp 4.
> upgrade UI bundle

- etc/nginx/snippets/rewrites.conf
(both had releases whilst I was away)
> DOC-5738 Updating Python & Node.js API links

- Dockerfile.jenkins
- netlify/package-lock.json
- netlify/package.json
- package-lock.json
- package.json
- configure package.json to automatically grab latest patch release
> upgrade to Antora 2.0.1

- staging-antora-playbook.yml
> Including new ngdm repo

- production-antora-playbook.yml
- staging-antora-playbook.yml
Include UI package and global attributes from [docs-ui #70](https://github.com/couchbase/docs-ui/pull/70)
Documentation issue: [DOC-5052](https://issues.couchbase.com/browse/DOC-5052)
> DOC-5052: Version labels and edition labels in body text

- home/modules/ROOT/pages/index.adoc
Changes getting-started.adoc to gs-sgw-install.adoc
> DOC-6341-Correct-Broken-Alias-Link

- antora-playbook.yml
Docs issue: [DOC-6816](https://issues.couchbase.com/browse/DOC-6816)
> DOC-6816: Update Antora infrastructure for release/6.6

- Jenkinsfile
- antora-playbook.yml
Requires https://github.com/couchbase/docs-ui-sandbox/pull/54
> Update optanon script

- etc/nginx/snippets/rewrites.conf
> txns updated path

- home/modules/contribute/pages/repositories.adoc
> Added Scala

- home/modules/ROOT/pages/index.adoc
Bullet points on home page were not rendering properly, and other minor issues.
Preview build here https://simon-dew.github.io/docs-site/DOC-7180/home/index.html
> Fix markup issues on home page

- home/modules/contribute/pages/test-site.adoc
> Lightweight Local Playbook

- home/modules/contribute/pages/create-branches.adoc
> 6.5 --> 6.6

- home/modules/contribute/pages/code-blocks.adoc
> code samples & SDKs

- home/modules/contribute/examples/local-staging-antora-playbook.yml
> minimalist local playbook

- README.adoc
> linking local playbook

- antora-playbook.yml
Add release/2.8 branch to antora-playbook.yml
> Add mobile 2.8 branches to staging build

- home/modules/contribute/examples/code-blocks.adoc
- home/modules/contribute/pages/attributes-and-roles.adoc
- home/modules/contribute/pages/basics.adoc
- home/modules/contribute/pages/code-blocks.adoc
- home/modules/contribute/pages/cross-references.adoc
- home/modules/contribute/pages/send-pr.adoc
- home/modules/contribute/pages/test-site.adoc
Main changes for review:
* [AsciiDoc Basics › URLs](https://deploy-preview-270--cb-docs-staging.netlify.app/home/contribute/basics.html#urls)
* [Cross References › Cross Reference Best Practices](https://deploy-preview-270--cb-docs-staging.netlify.app/home/contribute/cross-references.html#cross-reference-best-practices)
* [Code Blocks and Callouts › Callout Numbers](https://deploy-preview-270--cb-docs-staging.netlify.app/home/contribute/code-blocks.html#callouts)
Doc issue: [DOC-7344](https://issues.couchbase.com/browse/DOC-7344)
> DOC-7344: Updates to Contributor's Guide

- home/modules/ROOT/pages/index.adoc
> Added earlier Ruby

- home/modules/ROOT/pages/sdk.adoc
> Absolute path for SDK doctor xref

- antora-playbook.yml
> K8S-1822: Make Operator 2.1 Live (Staging)

- antora-playbook.yml
This branch has since been merged in to master
> Update tutorial branches

- antora-playbook.yml
https://issues.couchbase.com/browse/DOC-8240
> DOC-8240-C4 Add Mobile Release 3.0 to Staging Builds

- antora-playbook.yml
* upgrade UI that includes search filter and other search enhancements
> roll out search enhancements, including search filter, to production

- antora-playbook.yml
Add in 2.3 and move 2.2 to the 2.2.x branch.
> K8S-2234: Operator 2.3.0 - Staging

- antora-playbook.yml
> K8S-2234: Operator 2.2.0 Live

- antora-playbook.yml
Supersedes https://github.com/couchbase/docs-site/pull/371
> Cloud Docs 

- antora-playbook.yml
> SDK-Common update

- antora-playbook.yml
- etc/nginx/snippets/rewrites.conf
- home/modules/ROOT/pages/sdk.adoc
- home/modules/contribute/examples/local-staging-antora-playbook.yml
I've grouped together https://github.com/couchbase/docs-site/pull/377/
https://github.com/couchbase/docs-site/pull/378/
https://github.com/couchbase/docs-site/pull/379/
in one.
> Kotlin; 3.2SDKs, Kafka+ES

- antora-playbook.yml
Update the UI bundle to include these changes: 
- https://github.com/couchbase/docs-ui/pull/119 
- https://github.com/couchbase/docs-ui/pull/117
> Upgrade UI to v127 for nodejs and typescript language highlight changes

- antora-playbook.yml
https://issues.couchbase.com/browse/DOC-9047
> DOC-9047-C26 -- Add release/3.0 to playbook

- home/modules/contribute/pages/attributes-and-roles.adoc
> :page-alias: example

- antora-playbook.yml
Go too excited and forgot to amend the below PR after confirming that the test to make the build fail and output logs was successful!
https://github.com/couchbase/docs-site/pull/421/files
> Revert output log failure test.

- antora-playbook.yml
Let's see how fast these builds can go! 🐎
> Keep latest branches only and comment out unnecessary repos

- scripts/populate-icon-defs.js
Added section to populate font awesome light icons.
> Adding section to populate font awesome light icons.

- antora-playbook.yml
Temporarily remove release/3.0 tp avoid dup nav error
> QF220110-3 -- Add 3.0 GA Release feature branch

- antora-playbook.yml
Updating the staging server to the lastest version of the UI.
This is mainly for enhancements for the external icon CSS.
> Update staging server to prod-142 UI

- antora-playbook.yml
Moving older backup and analytics to archive
> [rayoffiah] adding-5x-and-5.5x-to-archive

- Jenkinsfile
Adding sudo clause to the npm call. Hopefully fixes permissions issue.
> Adding sudo to install

- antora-playbook.yml
Add tableau connector to staging branch
Docs issue: [DOC-9255](https://issues.couchbase.com/browse/DOC-9255)
> DOC-9255: Document Tableau BI Connector

- home/modules/contribute/examples/local-staging-antora-playbook.yml
> Versions update

- antora-playbook.yml
https://issues.couchbase.com/browse/DOC-9266
> DOC-9266 -- includ eCouchbase Mobie Workshop

- antora-playbook.yml
Replace 'feature/3.0-GA' build with build from  Release/3.0
https://issues.couchbase.com/browse/DOC-9266
> DOC-9266 -- Update from 3.0.0-beta02 to 3.0 GA

- antora-playbook.yml
https://issues.couchbase.com/browse/DOC-9266
(cherry picked from commit d228202e1ad578d7c2704dc6c29870b9647dd809)
> DOC-9266 -- include Couchbase Mobile Workshop

- antora-playbook.yml
- home/modules/ROOT/pages/cloud.adoc
- home/modules/ROOT/pages/index.adoc
- home/modules/contribute/pages/repositories.adoc
- home/modules/contribute/pages/word-list.adoc
Setting this up here now, so that we are ready whenever the release goes ahead!
> Prepare CMOS for DP release

- home/modules/ROOT/pages/index.adoc
See https://docs-staging.couchbase.com/home/index.html
> Removing inVPC

- antora-playbook.yml
> [NO ISSUE] Revert attribute for query language

- Jenkinsfile
As per Dan's suggestion I'm updating the failure routine logic to help clear some space on Jenkins...
> Update failure routine

- Jenkinsfile
Doesn't seem to be working, so at this point I'm going to revert to what was there initially.
> Revert delete directory attempts

- antora-playbook.yml
Also removes 2.3.0-beta as "I consider it part of 2.3 at this point in
time." -Rainbow Sr
> Release 2.3.0 for staging

- antora-playbook.yml
Removing out of date course until updated
> QF220412-2 -- Remove unused courses

- antora-playbook.yml
Getting this ready for the 2.3 release.
We should merge this as soon as we're ready to go live.
> [PRODUCTION] - Release Operator 2.3.0

- antora-playbook.yml
> Capella in top nav

- antora-playbook.yml
- home/modules/ROOT/pages/sdk.adoc
remove 2.7's 6.0 common
DOC-9992
> 3.3 jvm releases

- antora-playbook.yml
- etc/nginx/snippets/rewrites.conf
- home/modules/ROOT/pages/sdk.adoc
- home/modules/contribute/examples/local-staging-antora-playbook.yml
> 3.3 JVM SDK releases

- antora-playbook.yml
- etc/nginx/snippets/rewrites.conf
- home/modules/ROOT/pages/sdk.adoc
- home/modules/contribute/examples/local-staging-antora-playbook.yml
Just getting this ready, not sure when this will be out but prepping this for now.
> Prep Go release 2.5

- antora-playbook.yml
> NO ISSUE: Add release/7.1 and neo branches to prod

- antora-playbook.yml
See https://github.com/couchbase/docs-ui/pull/136
see https://github.com/couchbase/docs-site/pull/562 for master branch
> Update UI to 146, for meta robots feature

- antora-playbook.yml
Update main branch to use UI package 148
> DOC-9410: UI Changes for code blocks

- home/modules/contribute/examples/local-staging-antora-playbook.yml
- home/modules/contribute/nav.adoc
- home/modules/contribute/pages/build-site.adoc
- home/modules/contribute/pages/install-antora.adoc
- home/modules/contribute/pages/install-git-and-editor.adoc
- home/modules/contribute/pages/playbook.adoc
- home/modules/contribute/pages/test-site.adoc
https://issues.couchbase.com/browse/DOC-9882
> DOC-9882 Update installation instructions on the Docs Site

- home/modules/contribute/pages/install-antora.adoc
Noticed a typo when I was browsing the docs for the Couchbase contributing flow. Figured I'd give it a shot and give a quick PR to fix the issue!
> Fixed typo noticed in install-antora.adoc

- Dockerfile.jenkins
- antora-playbook.yml
Adding the callout package to the staging site.
> DOC-10175 Add asciidoctor-external-callout extension to site.

- .gitignore
- antora-playbook.yml
- lib/asciidoctor-callout-list-block.js
https://github.com/asciidoctor/asciidoctor/issues/3359
> Adding extension to enable callouts without associated listing block (for staging).

- antora-playbook.yml
Change to staging to check change.
> DOC-10357 CAO: Update SG docs to use bootstrap config

- antora-playbook.yml
Changing staging to demonstrate a change.
> DOC-10357-demonstration-2

- etc/nginx/snippets/rewrites.conf
Release Java SDK 3.3.4, jvm-core 2.3.4, and Scala 1.3.4.
> Java 3.3.4, Jvm Core 2.3.4, Scala 1.3.4, and Kotlin 1.0.4

- home/modules/ROOT/pages/sdk.adoc
- Update "xrefs" to link to the current component version, instead of referencing a specific one.
- Add spacing above "Server SDKs" heading.
- Add Discord link to landing page.
> [NO-JIRA] - Minor landing page fixes/updates

- antora-playbook.yml
https://github.com/couchbase/docs-ui/commit/d9467a167ec308c85d90f037045d755a087a92d4
This updates the UI bundle to support the page type tags change. Starting with staging so we can test it out.
> Update the ui bundle to prod-154

- antora-playbook.yml
Update ui bundle so we can view the https://github.com/couchbase/docs-ui/pull/153 changes in staging.
> Update ui bundle to prod-155

- antora-playbook.yml
Adds tag UI changes to prod - https://github.com/couchbase/docs-ui/pull/154
> Update ui bundle to prod-156

- Jenkinsfile
Seems like *production* still doesn't work, despite *staging* being fine (and showing icons as expected).
Back to the drawing board...going to revert changes.
> Revert fontawesome changes

- Jenkinsfile
Now that Ray has obtained a new fontawesome token for us, this should work.
> Uncomment icon script step

- antora-playbook.yml
AV-46170---Oct-30th-Docs-release-branch
> AV-46170 Point staging to Oct-30th release

- antora-playbook.yml
Replaces sqlpp with SQL++ in code block labels
> NO ISSUE: Update prod to 160

- antora-playbook.yml
- etc/nginx/snippets/rewrites.conf
Kotlin to come a little bit later..
> Java and Scala Releases

- home/modules/ROOT/pages/index.adoc
> Updating ZD creds

- antora-playbook.yml
* Add separate branches for 7.2 prerelease and 7.1
* Remove branches for 6.0
Docs issue: [DOC-10775](https://issues.couchbase.com/browse/DOC-10775)
> DOC-10775: Docs infrastructure for 7.2.0

- antora-playbook.yml
Now that I've come back to this, just want to update the UI bundle to change the [abstract] styling.
> Update antora-playbook.yml to use new UI release

- antora-playbook.yml
to test https://github.com/couchbasecloud/couchbase-cloud/pull/18906/
> Test provisioned (single branch) layout

- etc/nginx/snippets/rewrites.conf
> Testing tutorials rewrite

- antora-playbook.yml
Ready for release/7.2 GA
See docs issue for other GA release tasks: [DOC-11066](https://issues.couchbase.com/browse/DOC-11066)
> DOC-11066: Add release/7.2, neo branches to prod

- home/modules/contribute/pages/repositories.adoc
Porting #686 to the staging site.
Docs issue: [DOC-11097](https://issues.couchbase.com/browse/DOC-11097)
> DOC-11097: Private repos in the contributor guide

- antora-playbook.yml
Follow-up to #676 
Docs issue: [DOC-11066](https://issues.couchbase.com/browse/DOC-11066)
> DOC-11066: Add capella branch for docs-devex

- home/modules/ROOT/pages/sdk.adoc
Getting rid of legacy https://docs.couchbase.com/server/current/sdk/overview.html
> Landing page tidy up

- home/modules/contribute/pages/extensions-template.adoc
- lib/helpers/eq.js
- lib/helpers/ne.js
- lib/template-block.js
- test-remote.yml
required for https://github.com/couchbase/docs-server/pull/3295/
> template-helpers

- antora-playbook.yml
- home/modules/contribute/pages/extensions-template.adoc
- lib/template-block.js
- package-lock.json
- package.json
required for AV-54492 https://github.com/couchbasecloud/couchbase-cloud/tree/AV-54492-Management-API-Documentation
> prod-175 & other changes for AV-54492

- antora-playbook.yml
Added .NET SDK branch release/3.5 to file.
> Updated file with .NET SDK release/3.5 branch

- etc/nginx/snippets/rewrites.conf
Updated .NET SDK version to 3.5.0 in order to publish updated release notes.
> Updated .NET SDK version to 3.5.0

- antora-playbook.yml
See https://github.com/couchbaselabs/docs-columnar/pull/51.
> AV-76422: Add attribute token for columnar-flavored SQL++

- antora-playbook-staging.yml
- antora-playbook.yml
- lib/antora-component-version-rank.js
For Algolia. 
The UI change is https://github.com/couchbase/docs-ui/commit/ef59d72ded505298e356e25e1ec348587912ba57
(in prod-180)
Happy to discuss on Slack/Zoom
> Add version rank and point to new search UI bundle

- home/modules/contribute/examples/description-lists.adoc
- home/modules/contribute/examples/footnotes.adoc
- home/modules/contribute/examples/inline-styles.adoc
- home/modules/contribute/examples/links.adoc
- home/modules/contribute/pages/add-pages.adoc
- home/modules/contribute/pages/attributes-and-roles.adoc
- home/modules/contribute/pages/basics.adoc
- home/modules/contribute/pages/install-git-and-editor.adoc
- home/modules/contribute/pages/pages.adoc
- home/modules/contribute/partials/available-attributes.adoc
Draft PR for keeping track of writer's guide updates.
Creating for keeping in sync with @osfameron
> Writers Guide Updates - Sarah's Contributions

- antora-playbook-staging.yml
- antora-playbook.yml
To point build at new docs-capella repo once
https://github.com/couchbasecloud/couchbase-cloud/pull/30453 is merged.
> AV-76530 extract capella docs

- antora-playbook.yml
Following on from:
* https://github.com/couchbase/docs-ui/pull/187
> Update UI bundle to 197

- antora-playbook.yml
- home/modules/ROOT/pages/cloud.adoc
https://couchbasecloud.atlassian.net/wiki/spaces/DOCS/pages/2356609026/Columnar+GA+week+of+2024+8+5+Go+Live+checklist
> AV-77309 Columnar GA

- antora-playbook.yml
- etc/nginx/snippets/rewrites.conf
- home/modules/ROOT/pages/columnar-sdk.adoc
- home/modules/ROOT/pages/sdk.adoc
> Columnar SDKs release

- home/modules/contribute/pages/index.adoc
> Cloud JIRA link update

- antora-playbook-staging.yml
- antora-playbook.yml
and minor drivebys to main playbook.
> update staging playbook

- antora-playbook-staging.yml
- antora-playbook.yml
> Superset Release 1.0.5

- antora-playbook.yml
> Quarkus GA

- antora-playbook.preview.yml
This pull request incorporates the Superset connector repository into the Antora preview playbook. The `release/1.0` branch has been added, enabling the Superset connector documentation to be part of the preview build process.
> Include Superset connector in Antora preview playbook

- antora-playbook-staging.yml
Add Sync Gateway 3.3 to docs staging build
> DOC-13292: Sync Gateway 3.3
