couchbase/docs-site

- production-antora-playbook.yml
- staging-antora-playbook.yml
The convention is that any repository that is public should be accessed via HTTPS, whereas any repository that is private should be accessed via SSH. This is also how the UI determines whether to offer an edit on GitHub button.
> reference sdk repos using public URL in playbook

- production-antora-playbook.yml
- staging-antora-playbook.yml
update Couchbase Lite branches and include release/2.5 in staging playbook.
> update Couchbase Lite branches and include release/2.5 in staging playbook.

- docsearch/Dockerfile.jenkins
- docsearch/Jenkinsfile
Leverage the Docker support in Jenkins to drastically simplify the build script that runs the docsearch scraper.
> Dockerize the docsearch-scraper CI job

- home/modules/contribute/pages/cross-references.adoc
It's important to have examples that show how to link within a module that has a nested directory structure, especially since several of our modules are organized this way.
> Added more examples of linking within a module

- production-antora-playbook.yml
The Operator repo forked for version 1.2.x. This commit replaces master with 1.2.x.
> Update production playbook with new Operator branch

- staging-antora-playbook.yml
This commit updates the staging playbook with the new Operator 1.2.x branch. Before this PR can be merged, antora.yml on the master branch in the Operator repo needs to be updated to a newer version, otherwise the build will fail. That change is staged in Gerrit.
> Update staging playbook with new Operator branch

- production-antora-playbook.yml
- staging-antora-playbook.yml
https://issues.couchbase.com/browse/DOC-4138
docs-ui v216 contains:
- a fix for to remove the "View Latest" banner tutorials.
Example:
https://deploy-preview-91--cb-docs-staging.netlify.com/userprofile-couchbase-mobile/standalone/userprofile/userprofile_basic.html
https://deploy-preview-91--cb-docs-staging.netlify.com/userprofile-couchbase-mobile/query/userprofile/userprofile_query.html
(known issue: the banner is still visible on the Android and Xamarin tutorials, I will add the page attribute there after this PR is merged).
- a fix to remove the version dropdown on the `tutorials` and `userprofile-couchbase-mobile` components and show a link to the tutorials home page instead.
Example:
https://deploy-preview-91--cb-docs-staging.netlify.com/tutorials/session-storage/install.html
etc.
> DOC-4138 - Tutorials version dropdown

- home/modules/contribute/pages/send-pr.adoc
Adding links to GitHub Help to make it easier for us to find them and include them as distinct steps in the contribution process.
> Add PR review and Incorporating suggestions sections

- home/modules/ROOT/partials/developer-preview.adoc
- home/modules/contribute/examples/developer-preview.adoc
- home/modules/contribute/pages/includes.adoc
Follow up from @simon-dew's commit [27cad2b](https://github.com/couchbase/docs-server/commit/ab6d3eafa331bb66a04f87b28281a0837517e4a4#diff-27cad2b57b742b638d75023b6acfe0ff) which adds a partial in the `server` component.
This PR adds a slightly modified version of that partial to the `ROOT` module in the `home` component and documents a usage example.
I've removed the h2 and xref to the developer preview mode page (specific to CB Server) although we could certainly add those back in in a sub-sequent PR with their respective usage examples.
Preview: https://deploy-preview-109--cb-docs-staging.netlify.com/home/contribute/includes.html#couchbase-documentation-partials
> Dev preview partial

- production-antora-playbook.yml
- staging-antora-playbook.yml
Publish docs for Elasticsearch connector 4.1.x from the master branch.
> Release Elasticsearch 4.1 documentation

- etc/nginx/snippets/rewrites.conf
- production-antora-playbook.yml
- staging-antora-playbook.yml
Modifications
-------------
Get Elasticsearch connector 4.1 docs from branch `release/4.1`.
Get 4.2 docs from branch `master`.
Update current version to 4.2.
> Update for Elasticsearch connector 4.2

- home/modules/ROOT/pages/index.adoc
This change is a stopgap to paint over the the major page alias issues that are occurring in the Java SDK 3.0 docs.
> Update homepage xrefs to point to new Java pages

- home/modules/ROOT/pages/index.adoc
Add in an additional link to Couchbase Mobile from the Docs page, namely:
link to the :sync-gateway::cbmintro.adoc page, which acts as a shared Couchbase Mobile landing-page accessible from SGW and, eventually, CBL.
> DOC-6341-Add link to a couchbase mobile landing page

- production-antora-playbook.yml
For AO, replaced master branch with the 2.0.x branch.
> Replace Operator master branch with 2.0.x branch

- antora-playbook.yml
For AO, add 2.0.x branch, as master will now carry forward minor releases.
> Add Operator 2.0.x branch to staging

- home/modules/ROOT/pages/developer.adoc
Tip of the hat to @mgroves who saw that on windows that scrollbars
appear in the blue logos panel and looks ugly. On Mac, in contrast,
scrollbars are normally hidden.
> developer.adoc - no scrollbars for user logos, esp. for windows

- home/modules/ROOT/pages/developer.adoc
The only SDK not called out.
Scala carries a lot of developer appeal above and beyond its actual use.
> Scala SDK link

- antora-playbook.yml
Motivation
----------
master branch is now being used for 4.0 development
> Build Kafka 3.4 docs from release/3.4 branch

- antora-playbook.yml
Add cb-swagger repo for REST API documentation. (This won't work until all related changes have been merged in the `docs-server` repo, for branches `release/6.0`, `release/6.5` and `release/6.6`.)
Docs issue: [DOC-7395](https://issues.couchbase.com/browse/DOC-7395)
> DOC-7395: Use cb-swagger repo for REST API doc partials

- antora-playbook.yml
- Update top banner: Move link to .com to icon, update label from Try Now to Downloads, 
- Add home icon to top (blue) menu
- Fix anchor ids not resolving on Chrome
- Update code block highlighting colors for yellow and light grey
> Bump UI bundle version for fixes

- antora-playbook.yml
[SBEE-32](https://issues.couchbase.com/browse/SBEE-32)
Now that we've [branched](https://github.com/couchbase/docs-service-broker/tree/1.0.x) the 1.0 release of `docs-service-broker`, we need to update the staging docs site to point to this new branch so that we can begin adding CSB 1.1 content to master.
> SBEE-32: Move CSB 1.0 to its own branch (staging)

- antora-playbook.yml
WARNING! The following PR must be merged first:
- https://github.com/couchbase/docs-site/pull/354
[SBEE-32](https://issues.couchbase.com/browse/SBEE-32)
Now that we've [branched](https://github.com/couchbase/docs-service-broker/tree/1.0.x) the 1.0 release of `docs-service-broker`, we need to update the prod docs site to point to this new branch so that we can begin adding CSB 1.1 content to master.
NOTE: The immediate next step will be to [update `antora.yml` to version `1.1`](https://github.com/couchbase/docs-service-broker/blob/master/antora.yml#L3) on the master. After that, we can update the docs-staging playbook to include both `master` and `1.0.x` branches.
> SBEE-32: Move CSB 1.0 to its own branch

- antora-playbook.yml
WARNING! The following PR must be merged first:
- https://github.com/couchbase/docs-service-broker/pull/3
[SBEE-32](https://issues.couchbase.com/browse/SBEE-32)
Now that we've [branched](https://github.com/couchbase/docs-service-broker/tree/1.0.x) the 1.0 release of `docs-service-broker`, we need to update the staging docs site to point to both the `master` (1.1) and `1.0.x` (1.0) branches.
> SBEE-32: Add CSB 1.1 to staging

- antora-playbook.yml
Since there has been no declared version for the next release of the Couchbase Service Broker, I've gone ahead and matched the branches in the staging playbook with those in the production playbook. I will add master back to the staging playbook once a plan is in place for the next CSB release. Until then, removing master from the staging playbook reduces the risk of failed builds.
> Service Broker: Update staging to match production

- antora-playbook.yml
Update the UI bundle to support language highlighting for the `nodejs` alias and the addition of `typescript`.
> Update UI to v127 for language highlighting changes

- antora-playbook.yml
Sets the minimum width of the search results to 50vw so it doesn't shrink when the screen width is between 769px and 1024px.
> upgrade UI to fix width of search results between 769px and 1024px

- antora-playbook.yml
Build temporary branch to keep track of dev-reorg project.
Docs issue: [DOC-9195](https://issues.couchbase.com/browse/DOC-9195)
> DOC-9195: Enable New Couchbase Developers

- antora-playbook.yml
- netlify/netlify.toml
Cat seems to generate only ~920 lines of output, which is just 3%
of the 34,000 the local Netlify docker build image produces.
> tail antora log on failure

- antora-playbook.yml
Second attempt. Removing all versions earlier than 6.0 from the staging site to cut down on build times, given that version 5.5 is now unsupported.
UPDATE: removing all versions earlier than 6.0 didn't work, but removing `dev-reorg` did. Seems we can't have `dev-reorg` and `release/7.1` at the same time.
> [NO ISSUE] build version 7.1 on staging site

- antora-playbook.yml
This adds :page-toclevels: support.
> Update to docs-ui bundle 135

- antora-playbook.yml
Apologies, this should have been part of
https://github.com/couchbase/docs-site/pull/427
However this isn't urgent, as (different to Antora default), we
set the default levels to 1:
https://github.com/couchbase/docs-ui/pull/126/commits/301699460a541d52157af31923400e4594c6ddf6
This config change simply declares this as a default, which can be overridden
by pages as per:
https://github.com/couchbase/docs-sdk-java/commit/e3dc20c8462228bdc4e9348e7801c8af5936d2b7
> Configure default page-toclevels

- etc/nginx/snippets/rewrites.conf
Reverting 45c53ec9ba25bd66edbb48459e45dfc88571af7d  
Now that https://issues.couchbase.com/browse/NCBC-3011 is fixed
> Unrevert dotnet SDK change, back to 3.2.4

- antora-playbook.yml
- home/modules/ROOT/pages/cloud.adoc
- home/modules/ROOT/pages/index.adoc
- home/modules/contribute/pages/repositories.adoc
- home/modules/contribute/pages/word-list.adoc
Setting up our staging site with CMOS docs, let's see if I break anything 😄 , hopefully it should just work(tested on local and seemed fine).
Also added a change in [cloud-native-database](https://github.com/couchbase/docs-cloud-native/pull/24) to setup the left hand nav title.
> DOC-9421 - Add CMOS project to site [STAGING]

- home/modules/ROOT/pages/sdk.adoc
https://issues.couchbase.com/browse/DOC-9449
The new Nodejs 3.2 API doc front page seems quite confusing for users, let's point directly to the modules page where all the objects and functions are listed.
> [DOC-9449] - Point to modules page in Node.js API doc

- scripts/package.json
- scripts/populate-icon-defs.js
Made a change to the doc site so that the light elements of Font awesome can be used.
> Retrieve light icon set for fontawesome

- antora-playbook.yml
Moved these to the archive site in a separate PR (433)
> Doc 9391 – moving release/5.5, release/5.1 and release/5.0 to archive master branch

- antora-playbook.yml
The build is a bit smashed because https://github.com/couchbaselabs/userprofile-couchbase-mobile-android has its content located in a subdirectory. 
Fixing the playbook so that it can find it.
> Fixing location for mobile-android content

- antora-playbook.yml
- package.json
Note that the sdk-commons docs still need 5.5 due to existing dependencies.
> [rayoffiah] archiving 5.0x and 5.5x

- Jenkinsfile
So, no sudo, so we'll try just removing the global install clause, and see if it can still pick up the module.
> removing global from kroki install

- antora-playbook.yml
Netlify choking because it can't access our Kroki servers. Removed the Kroki installation from Staging.
> rayoffiah-remove_kroki_from_staging

- antora-playbook.yml
We should not change the name of the query language until (a) we have introduced this attribute consistently across the entire documentation set, as far as possible; and (b) the plan to change the name has actually been finalized.
> [NO ISSUE] Revert attribute for query language

- home/modules/ROOT/pages/server.adoc
- home/modules/contribute/pages/word-list.adoc
For Neo release.
* The references to `7.0` on the server landing page are all to do with upgrading to use scopes and collections, so I have replaced with `7.x` for more generic relevance. We can revisit this for 8.x 😉 
* Replaced references to `7.0` in the wordlist with a more generic `n.n`
> NO ISSUE: Remove references to 7.0

- antora-playbook.yml
- home/modules/contribute/pages/extensions.adoc
- lib/markdown-block.js
Block extension to filter text like:
[markdown]
--
Filter some text with [Markdown](https://commonmark.org/help/) syntax.
--
This is not implemented with a full Markdown parser.
See https://github.com/asciidoctor/kramdown-asciidoc/issues/7
with a link to the "naive series of regexes" used as starting point.
(And note that we use Open structural context
https://docs.asciidoctor.org/asciidoc/latest/blocks/delimited/#summary-of-structural-containers
with `--` delimiters, and headings don’t work inside these.)
This feature is intended for handling OpenAPI specs, which can contain Markdown,
however openapi-generator has poor Asciidoc handling
https://github.com/OpenAPITools/openapi-generator/issues/11396
so instead we add the block delimiters in the template, and let the block filter handle …
> Asciidoc markdown block

- antora-playbook.yml
- home/modules/contribute/pages/extensions.adoc
- lib/markdown-block.js
after #572 merged to Staging.
Block extension to filter text like:
[markdown]
--
Filter some text with [Markdown](https://commonmark.org/help/) syntax.
--
This is not implemented with a full Markdown parser.
See https://github.com/asciidoctor/kramdown-asciidoc/issues/7
with a link to the "naive series of regexes" used as starting point.
(And note that we use Open structural context
https://docs.asciidoctor.org/asciidoc/latest/blocks/delimited/#summary-of-structural-containers
with `--` delimiters, and headings don’t work inside these.)
This feature is intended for handling OpenAPI specs, which can contain Markdown,
however openapi-generator has poor Asciidoc handling
https://github.com/OpenAPITools/openapi-generator/issues/11396
so instead we add the block delimiters in the template, and …
> Asciidoc markdown block (merge to prod)

- etc/nginx/snippets/rewrites.conf
- Java 3.3.2
- Scala 1.3.2
- Python 4.0.2
> Java, Scala, and Python releases

- antora-playbook.yml
(master branch will soon be 4.4)
> Build Elasticsearch connector 4.3 docs from branch release/4.3

- antora-playbook.yml
This reverts commit 015e226a2ac239ab22018ab37dfd5751db48bbd9.
(To test on staging that Capella release is correct against main)
> Revert "AV-39681 stage July 2022 changes for capella (#586)"

- antora-playbook.yml
Don't merge this yet, waiting for this to go in for Monday 1st August 2022.
> Build Elasticsearch connector 4.4 docs from master branch

- Jenkinsfile
This is currently causing our build to fail, we have opened a ticket for OpenDevise, but we need to be able to publish the site whilst we wait.
For the moment, what will happen is that fontawesome icons will not show, there may be other side effects which I am probably not aware of. At the very least I hope this will allow us to publish the docs.
I have tested on staging, and it seems to behave the way I expected (i.e, the icons don't show but everything else seems fine).
> Comment out icons script

- Jenkinsfile
It's possible that when IT recently sorted the Jenkins disk space issues, the information needed for fontawesome was somehow lost. https://couchbase-internal.zendesk.com/hc/en-us/requests/11756
Ray has added the `FONTAWESOME_NPM_AUTH_TOKEN` env variable on the Jenkins box (via ssh) in ~/.profile, so that should be permanently available for Jenkins to use for fontawesome.
This has been tested on `staging` and the icons are showing successfully, so I'm making this change in prod now.
> Add icon script back in steps and update fontawesome token variable

- Dockerfile.jenkins
- lib/exclude-private-content-sources-extension.js
- lib/source-url-include-processor.js
NOTE: staging doesn't use the netlify/package.json etc., so they've not been included.
> upgrade to Antora 3.1

- Dockerfile.jenkins
- lib/exclude-private-content-sources-extension.js
- lib/source-url-include-processor.js
This reverts commit 2c33077f88d46ea8ee93ba52c7a9cefe4c97bfe2.
see e.g. https://docs-build.sc.couchbase.com/job/Antora/job/docs.couchbase.com/job/staging/278/console 3 fails, which may be unrelated as staging not built for 6 days
> Revert "upgrade to Antora 3.1 (#649)"

- antora-playbook.yml
Follow-up change to #653 — use the `7.1.x-docs` branch for the backup and couchbase-cli docs for release 7.1.
Docs issue: [DOC-10775](https://issues.couchbase.com/browse/DOC-10775)
> DOC-10775: Docs infrastructure for 7.2.0

- antora-playbook.yml
Adds the docs-devex repo to the `staging` playbook, before cloud and server. See also:
* [couchbase/docs-server#3069](https://github.com/couchbase/docs-server/pull/3069)
* [couchbaselabs/docs-devex#5](https://github.com/couchbaselabs/docs-devex/pull/5)
Docs issue: [DOC-10800](https://issues.couchbase.com/browse/DOC-10800)
> DOC-10800: Migrate how-to guides to docs-devex

- antora-playbook.yml
- home/modules/contribute/pages/extensions-embargoed.adoc
- home/modules/contribute/pages/extensions-flagged.adoc
- lib/embargo.js
See https://github.com/couchbase/docs-site/pull/643 for Live PR.
Note that instead of deleting `page.pub` and `page.out`, we could use `contentCatalog.removeFile(page)` but this requires:
* antora 3.1.1 or some release after https://gitlab.com/antora/antora/-/commit/36ae21fae5654b4f9443e6a5cc0a48006c9ec4d7
* We are testing upgrading to 3.1.1 https://support.opendevise.com/support/tickets/170 had some issues in staging. Had to comment out source-url-include-processor.js to run this locally
> AV-50499: Embargo Pages (STAGING)

- antora-playbook.yml
- home/modules/contribute/pages/extensions-embargoed-ok.adoc
- home/modules/contribute/pages/extensions-embargoed.adoc
- home/modules/contribute/pages/extensions-flagged.adoc
- lib/embargo.js
This requires:
* antora 3.1.1 or some release after https://gitlab.com/antora/antora/-/commit/36ae21fae5654b4f9443e6a5cc0a48006c9ec4d7
* looks like we're not ready to upgrade to that (notice how I've had to comment out source-url-include-processor.js to test this) and have pinged Opendevise https://support.opendevise.com/support/tickets/170
> AV-50499 embargo pages mockup

- home/modules/contribute/pages/repositories.adoc
* Move backup, operator, and analytics to new Private section
* Remove links to private repos
* Add link to AsterixDB repo
* Update analytics link for future use
* Add docs-devex and cb-swagger
* Add Couchbase to Server and Lite
Docs issue: [DOC-11097](https://issues.couchbase.com/browse/DOC-11097)
> DOC-11097: Private repos in the contributor guide

- docsearch/Jenkinsfile
- docsearch/hbs-helpers/versioned.js
- docsearch/hbs-helpers/versionless.js
1. use pinned working version of glob
2. edit `versioned` and `versionless` helpers to generate working config for Capella (this was broken by the Hosted/Provisioned config)
> Fixing docs-search 

- home/modules/ROOT/pages/sdk.adoc
Fixes the formatting appearing in running text
> remove leading whitespace

- antora-playbook.yml
This PR updates the staging playbook so that we can start building server release/7.6 in docs-staging.
* Removes EOL versions from the staging playbook following #702 
* Adds `release/7.6` branches for  `docs-devex`, `cb-swagger`, `docs-analytics`, and `docs-server`
* Adds note about `trinity` branches for `backup` and `couchbase-cli`
Note that `trinity` branches for `backup` and `couchbase-cli` are not ready yet, so these will not be included in 7.6 staging builds to begin with. Will need a new PR to add these when ready.
Docs issue: [DOC-11173](https://issues.couchbase.com/browse/DOC-11173)
> DOC-11173: Docs infrastructure for 7.6.0

- home/modules/ROOT/partials/info-banner.adoc
revert the Capella Spring Banner.
NB: 
* the calling points are left in place, so it should be trivial to edit this file to re-add the banner at any point in future
* we remove the inline CSS, which will now be added to docs-ui in PR https://github.com/couchbase/docs-ui/pull/167
> AV-56547: Revert Banner

- antora-playbook.yml
Time-saving fix to legacy 6.5 includes in SDK 3.1.
In later versions a variable ensures the correct include::, but not in 3.1.
> SDK Workaround

- home/modules/ROOT/pages/index.adoc
Adding tutorials link to DA site,
as the topnav tutorial link has been removed.
> Tutorials link

- etc/nginx/snippets/rewrites.conf
Via https://www.couchbase.com/forums/t/documentation-of-travel-sample-app-not-found/36258/2
We redirect /tutorials/ to developer.couchbase.com but the mobile tutorials were never adopted.
Until these are also adopted, this commit does `break` for known tutorials, to prevent the following redirect.
Test that e.g. https://docs-staging.couchbase.com/tutorials/todo-app/ is 404 (rather than 302 redirect).
The tutorials are published to live, e.g. see
https://github.com/couchbase/docs-site/blob/master/antora-playbook.yml#L130-L157 but not staging, hence the 404.
> Fix mobile tutorials redirects

- etc/nginx/snippets/rewrites.conf
`break` prevents the proxy_pass directive in the `default` site config. This workaround is inelegant but, well, works.
> Tutorials to S3 redirect

- scripts/make-global-sitemap.sh
@leeming produced a global-sitemap.xml for @gsauere and support team that contains *all* files, which is excessive for their indexing.
To do this in Antora would require overriding the `siteMap` function, for example to export an additional sitemap that includes only the latest version.
This is possible within Antora, but the default site-mapper doesn't export its utility functions, so we'd have to duplicate some logic, which could be fragile to future Antora updates.
Looking back at a command-line approach, while the sitemap xml files don't contain enough metadata to easily tell which version is current, we have an overridden site-generator (pimped up by OpenDevise) which exports a site-manifest.json:
https://gitlab.com/opendevise/oss/antora-site-generator-ms/-/blob/v2.3.x/lib/export-site …
> Global sitemap iteration

- antora-playbook.yml
Requires https://github.com/couchbase/docs-ui/pull/174 to be merged and prod-178 built against it.
> 2023 Rebrand: Update antora-playbook.yml to prod-178

- antora-playbook.yml
Add 7.6 branches (or `trinity` for those repos that use that convention).
Update UI bundle for Metrics display.
> DOC-11976: server 7.6 GA

- antora-playbook.yml
The SEO audit flagged a number of 4xx results.
Many of those are for API docs, generated by devs, and uploaded to our S3 bucket. Most of the 4xx errors are for *old* API docs, generated in the past using potentially old SDK docs toolchains. It may be awkward for devs to regenerate historical API docs.
This robots.txt change prevents crawlers such as Googlebot from indexing the OLD SDK API docs, which we hope should have a knock-on effect in reducing the number of 4xx errors generated.
We rely on the Evergreen links in https://github.com/couchbase/docs-site/blob/master/etc/nginx/snippets/rewrites.conf#L164-L181 which mean that e.g. https://docs.couchbase.com/sdk-api/couchbase-scala-client/ will transparently show (at current time) …
> AV-69254 robots.txt for SDK 4xx

- lib/embargo.js
Via Simon Dew, a page with page-aliases breaks page-embargo.
Looking at original commit, we were manually deleting page.pub etc. because the contentCatalog method was only present in Antora 3.1.1 and onwards. see 13190cefc6891db7500d086a1ddd09f13bb64bab
As we're now upgraded, we can substitute this in.
> DOC-12133 update page-embargo functionality

- antora-playbook.yml
Docs issue: DOC-10865
In the Server docs, the descriptions of the request-level settings are taken automatically from the Query Service REST API reference. I am assuming that, ultimately, the descriptions of request-level settings for Capella will be automatically generated from the Data API reference. However, the Data API is still in development.
As a temporary measure, this PR adds a cut-down version of the Query Service REST API to the (hitherto unused) `capella` branch of the cb-swagger docs, purely so that it can be used to generate descriptions of request-level settings for Capella.
⚠️ This change must be merged at the same time as the following related PRs:
* https://github.com/couchbaselabs/docs-devex/pull/216
* https://github.com/couchbasecloud/couchbase-cloud/pull/30942
* …
> DOC-10865: Migrate settings reference to docs-devex

- antora-playbook-staging.yml
- antora-playbook.yml
- home/antora.yml
- home/modules/ROOT/pages/cloud.adoc
- home/modules/ROOT/pages/index.adoc
- home/modules/ROOT/pages/integrations.adoc
- home/modules/ROOT/pages/mobile.adoc
- home/modules/ROOT/pages/sdk.adoc
- home/modules/ROOT/pages/server.adoc
For tweaking the search results, as follows:
50  the default for all pages, in the middle of the 0-100 range.
0  the writer's guide, to avoid promoting pages above more relevant content
75  each landing page, to promote it for the "no query" case.
The playbook and antora.yml cases are overrideable (@), allowing us to tweak each page individually.
UI is set to latest version which exposes `<meta name=docsearch:page_rank>` based on these values, such that Algolia will pick them up.
> AV-56565: add page-rank attribute

- etc/nginx/snippets/rewrites.conf
Test change to map 302 redirections to 301, which should allow them to be indexed by search engines. Testing on Staging first, in case it breaks.
> SEO-changes-map-302-to-301

- etc/nginx/snippets/rewrites.conf
Not sure how to go about testing this. I assume there must be some way to set up a fake harness to test a rewrites.conf change.
However, I am fairly confident that this won't break anything! 🤞🏾
> SEO change tutorials to permanent redirect

- antora-playbook-staging.yml
- antora-playbook.yml
Make Antora fetch remote updates to repositories:
https://docs.antora.org/antora/latest/playbook/runtime-fetch/
This will be a No-Op in most builds as:
* for Github Actions/Jenkins build, the environment is generated completely fresh every time, and Antora will always fetch the latest content in this case.
* most writers working locally will point to local repos, where this statement does nothing
So... what's the point? Well, the master playbooks are a resource that writers often copy, and having this as a default will help in the case that:
* Locally, you build with a remote repo, and don't update changes, leading to confusion and the gnashing of teeth.
(Those writers who use that workflow regularly have already added this to their playbooks, or have aliased antora to always use …
> quickfix: make fetch default in playbook

- antora-playbook.yml
We don't want the signpost and escape hatch to appear in the Capella operational docs until the Capella columnar docs have been published. For the moment, therefore, I've hidden the signpost and escape hatch behind a feature flag.
This PR _enables_ the feature flag for the columnar preview build, so that the signpost and escape hatch do appear in the Capella documentation for the columnar preview.
This must be merged at the same time as the following PR:
* https://github.com/couchbase/docs-capella/pull/38
> AV-82275: Add columnar Management API Guide

- antora-playbook.yml
New trademark wording via @jleatherCB 
Preview at https://preview.docs-test.couchbase.com/hakim.yml/home/index.html
(password at https://couchbasecloud.atlassian.net/wiki/spaces/DOCS/pages/1971224949/Docs+Team+demo+site+passwords )
The change is already in docs-ui 199 via https://github.com/couchbase/docs-ui/commit/e9306a92bf5d424b88b45be4e2a203e0fcaa0a23
This change to docs-site just points to new bundle prod-199
> DOC-12390 update trademark language

- antora-playbook-staging.yml
This must not be merged before confirmation from @malarky that master branch has been moved to track 2.8!
e.g. see https://github.com/couchbase/couchbase-operator/blob/master/docs/user/antora.yml#L3
> Update antora-playbook-staging.yml for operator 2.7 / 2.8

- home/modules/ROOT/pages/cloud.adoc
Adjusted an a line in the Capella homepage with free tier updates. Changed "free trial" with "free tier".
> [AV-82442] Update for Free Tier - Capella Homepage

- antora-playbook.yml
Updated the `antora-playbook.yml` file to reference the `prod-203` site UI.
> upgrade doc site ui to 203

- home/modules/contribute/pages/test-site.adoc
Just adding in some feedback received from other writer's getting a chance to review the writer's guide. 
Right now, that involves some clarity around Git Bash behaviour and sample code for configuring credentials with Antora.
> Writer's Guide Updates 2: Electric Boogaloo

- lib/preview.js
We already warned when the *current* content directory is not defined in antora-playbook.preview.yml.
But we didn't trap this error nicely in the ext.preview.sources case.
This commit extracts the `notfound` function so that both paths can throw a consistent error. (Of course the new case doesn't have all the information, so is a little hand-wavey...)
> Warn on undefined repo in ext.preview.sources

- antora-playbook-staging.yml
- antora-playbook.yml
We believe the "tutorials master" content is not linked or used. 
Tidied up commented-out sources.
> Remove unused tutorials sources, tidy up

- home/modules/contribute/examples/helpers/each-openapi.js
* complex arrays are treated as with `handleObject` but with square `[]` rather than curly `{}` braces.
* simple arrays are inlined `["string"...]` in a slightly hacky way... 🙈 
* the handler callbacks are all renamed to `handleX` for clarity
> improve each-openapi for arrays

- antora-playbook-staging.yml
- antora-playbook.yml
* `couchbase-operator` remains the source of truth for *generated* content built from dev artefacts.
* `docs-operator` contains all the handwritten docs, extracted from the monorepo.
Marked as DRAFT to merge only after Gerrit approval on `couchbase-operator` side.
> DOC-13085 extracted Operator to docs-operator

- etc/nginx/snippets/rewrites.conf
**Context:**
1) @malarky noted that pages like
BAD https://docs.couchbase.com/admin/admin/enterprise-edition.html
still exist and are indexed by Google.
2) most recent builds of those docs were replaced with an AWS S3 redirect file that would take you to the DA site, e.g.
404 https://developer.couchbase.com/documentation/server/3.x/admin/pdfs.html
3) ... those links are now unmaintained 404
4) But there are x13 files that were *moved or deleted* and therefore not replaced with those redirection links.
Those remain as **zombie* 200 files with bad content under /admin/admin
5) we have in the meantime restored our 3.x archive docs:
GOOD https://docs-archive.couchbase.com/docs-3x/admin/Couchbase-intro.html
**Solution:**
Step 1: this commit adds nginx rewrites to:
* rewrite zombie 200 files …
> DOC-13151 fix zombie 3.x docs issue

- package-lock.json
- package.json
Fixes an issue whereby the asciidoctor external callout extension was adding callouts globally, when it should have been adding them for the first match only.
> Fix for https://github.com/RayOffiah/asciidoctor-external-callout-js/issues/6

- antora-playbook.yml
Docs issue: [DOC-13291](https://jira.issues.couchbase.com/browse/DOC-13291)
This PR publishes the Sync Gateway 3.3 documentation.
Staging docs:
- [New In 3.3 › Release 3.3.0 (June 2025)](https://docs-staging.couchbase.com/sync-gateway/current/whatsnew.html#release-3-3-0-june-2025)
- [Sync Gateway Admin REST API Reference](https://docs-staging.couchbase.com/sync-gateway/current/rest_api_admin.html)
- [SG Collect Info](https://docs-staging.couchbase.com/sync-gateway/current/sgcollect-info.html)
- [Indexes](https://docs-staging.couchbase.com/sync-gateway/current/indexing.html)
- [Partitioned Indexes](https://docs-staging.couchbase.com/sync-gateway/current/index-partitions.html)
- [Release Notes](https://docs-staging.couchbase.com/sync-gateway/current/release-notes.html)
- [Supported …
> DOC-13291: Sync Gateway 3.3 Docs

- home/modules/contribute/pages/attributes-and-roles.adoc
- home/modules/contribute/partials/available-attributes.adoc
Enforce required attributes and establish :keywords: as required
> Update Contributor's Guide for Required Attributes

- antora-playbook-staging.diff.yml
- antora-playbook-staging.yml
- package-lock.json
- package.json
- scripts/patch-cutdown-playbook
Rationale: as well as the staging playbook, we now have to manage:
* the template preview playbook
* 1+ playbooks for chatbot
* escrow playbook
All of which need to be kept in sync with the main playbook, preserving just important differences.
As the staging playbook is the most high-profile one with likely the most complexity in setting it up, I'm starting with that, to check that we can do this fully enough to support the requirement.
(The preview one is currently supported by the more straight-forward scripts/patch-preview-playbook, but could use the same code.)
> DOC-13521 calculate staging playbook
